### ISSUE TITLE
mistake when multiple players

### ISSUE THREAD

**Issue by Robertuoftcs** [Raine-Yang-UofT/Infowar#4]
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3 /Users/tengli/Desktop/Infowar-main/Framework/client.py 
You are player 0
Waiting for other players...
Match found, start game...
Player 0  HP: 100/100  armor: 3/3
Information: 
Vision: 
Round 1  Please select your move:
1: move  2: sense  3: fire  4 gadget   (m: display map)1
Select the direction of movement
w: up  s: down  a: left  d: rightw
------------------------------
Player 0  HP: 100/100  armor: 3/3
Information: 
Move to (6, 3)
Vision: 
x  _  _  
_  R  _  
_  _  _  
Round 2  Please select your move:
1: move  2: sense  3: fire  4 gadget   (m: display map)m
Map: 
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  x  _  _  *  *  *  *  *  *  *  
*  *  *  *  *  _  R  _  *  *  *  *  *  *  *  
*  *  *  *  *  _  _  _  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  
1: move  2: sense  3: fire  4 gadget   (m: display map)1
Select the direction of movement
w: up  s: down  a: left  d: rights
------------------------------
Player 0  HP: 100/100  armor: 3/3
Information: 
Move to (6, 4)
Vision: 
_  _  _  
_  R  _  
_  #  _  
Round 3  Please select your move:
1: move  2: sense  3: fire  4 gadget   (m: display map)3
Select the weapon
1: assulter rifle  2: submachine gun  3: pistol  4: sniper_rifle  5: shotgun  1
Select the direction of firing:w: up  s: down  a: left  d: rights
------------------------------
Player 0  HP: 100/100  armor: 3/3
Information: 
Vision: 
_  _  _  
_  R  _  
_  #  _  
Round 4  Please select your move:
1: move  2: sense  3: fire  4 gadget   (m: display map)3
Select the weapon
1: assulter rifle  2: submachine gun  3: pistol  4: sniper_rifle  5: shotgun  5
Select the direction of firing:w: up  s: down  a: left  d: rights
------------------------------
Player 0  HP: 100/100  armor: 3/3
Information: 
Vision: 
_  _  _  
_  R  _  
_  #  _  
Round 5  Please select your move:
1: move  2: sense  3: fire  4 gadget   (m: display map)3
Select the weapon
1: assulter rifle  2: submachine gun  3: pistol  4: sniper_rifle  5: shotgun  5
Select the direction of firing:w: up  s: down  a: left  d: rights
Traceback (most recent call last):
  File "/Users/tengli/Desktop/Infowar-main/Framework/client.py", line 194, in <module>
    result = select_fire_command(net)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tengli/Desktop/Infowar-main/Framework/client.py", line 109, in select_fire_command
    return net.send(Message(net.get_player().get_id(), message.TYPE_FIRE, weapon.message, weapon, max(0, 100 - weapon.reaction_time)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tengli/Desktop/Infowar-main/Framework/network.py", line 49, in send
    self.player = pickle.loads(self.client.recv(2048 * 16))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: pickle data was truncated

Process finished with exit code 1

**Comment by Raine-Yang-UofT** [comment]
In the most recent update (v3.2.3 - alpha). This problem has not occurred during online testing
